foleys_licensing_client: NetworkRequest Class Reference
NetworkRequest Class Reference final
#include <foleys_NetworkRequest.h>
Public Member Functions
NetworkRequest (std::string_view url)
~NetworkRequest ()
void fetch (std::string_view newPayload)
void cancel ()
Public Attributes
std::function< void(int, std::string_view)> callback
std::string payload = ""
Static Public Attributes
static constexpr auto kUserAgent = L"foleys_license_win/1.0"
Constructor & Destructor Documentation
NetworkRequest()
NetworkRequest (std::string_view url) explicit
~NetworkRequest()
~NetworkRequest ()
References callback, and cancel().
Member Function Documentation
fetch()
void fetch (std::string_view newPayload)
References callback, cancel(), and payload.
cancel()
void cancel ()
References cancel().
Referenced by cancel(), fetch(), and ~NetworkRequest().
Member Data Documentation
kUserAgent
auto kUserAgent = L"foleys_license_win/1.0" static constexpr
callback
std::function<void (int, std::string_view)> callback
Referenced by fetch(), and ~NetworkRequest().
payload
std::string payload = ""
Referenced by fetch().
The documentation for this class was generated from the following files:
foleys_NetworkRequest.h
foleys_NetworkRequest.mm