foleys_licensing_client: SystemInfo Struct Reference
SystemInfo Struct Reference
#include <foleys_SystemInfo.h>
Static Public Member Functions
static std::string getAppData ()
static std::string getLocalAppData ()
static std::string createLicensePath (const char *manufacturer, const char *productName, const char *suffix=".lic")
Member Function Documentation
getAppData()
std::string getAppData () static
Returns
the application settings folder e.g. Application Support
getLocalAppData()
std::string getLocalAppData () static
Returns
the application settings folder e.g. Application Support, on windows the local
Referenced by createLicensePath().
createLicensePath()
std::string createLicensePath (const char * manufacturer, const char * productName, const char * suffix = ".lic") static
Parameters
manufacturer the manufacturer name as folder name under APP_DATA
productName the product name as license filename
suffix the suffix for the license filename including the dot
Returns
a path name for the license file
References getLocalAppData().
Referenced by LicensingDemoProcessor::LicensingDemoProcessor().
The documentation for this struct was generated from the following files:
foleys_SystemInfo.h
foleys_SystemInfo.cpp